version: '3'

services:
  app:
    build: .
    image: oracle/instantclient:12.2.0.1
    volumes:
      - "./goapp:/usr/local"
    container_name: go12c_app
    ports:
      - "8082:8080"
    tty: true
